// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xobptcvayfwruwltsccw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvYnB0Y3ZheWZ3cnV3bHRzY2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA1MDEsImV4cCI6MjA2NTQ5NjUwMX0.OckChSyHl1hEmlpuAtUyjVwMT611dl-Z7_L_GsZLwBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);